name: 🚀 Deploy Website via FTP

on:
  push:
    branches:
      - master

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  web-deploy:
    name: 🎉 Deploy Changes
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Carrega todo o histórico para o FTP deploy identificar os arquivos alterados corretamente

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_SERVER_DIR }} # Exemplo: public_html/ ou /home/lhsaia/confusa.top/
        state-name: ftp-deploy-sync-state.json
        # Lista de exclusão para arquivos que não devem ser enviados para a produção
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*/**
          **/.agents/**
          **/scratch/**
          README.md
          sitelookup_update07062019.sh
          **/.vscode/**
          **/hexacolor_repo/**
          **/PHPCompatibility-master/**
          **/full hexa suite/**
          **/sqlitedb/**
          **/session_data/**
          **/pngquant/**
          **/java_station/**
          **/myadmin/**
